sonar.projectKey=AlexanderPelaezJimenez_final-ci-cd
sonar.organization=alexanderpelaezjimenez
sonar.sources=app
sonar.python.version=3.12
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.flake8.reportPaths=flake8-report.txt
sonar.coverage.exclusions=**/tests/**,app/__init__.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
